url: "https://linuxgeek11.github.io"
baseurl: ""
title: "linuxgeek Tech Notes"

plugins:
  - jekyll-toc
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

toc:
  min_level: 1
  max_level: 3
  list_class: toc
  sublist_class: toc-sublist

repository: linuxgeek11/linuxgeek11.github.io

author:
  name: linuxgeek
  url: https://github.com/linuxgeek11
